// <auto-generated />
using System;
using LoyalKullaniciTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoyalKullaniciTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106080226_AddMuhasebeHareketleriTable")]
    partial class AddMuhasebeHareketleriTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Belgeler", b =>
                {
                    b.Property<int>("BelgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BelgeID"));

                    b.Property<string>("BelgeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BelgeKategoriID")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BelgeID");

                    b.HasIndex("BelgeKategoriID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Belgeler");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.EgitimBilgileri", b =>
                {
                    b.Property<int>("EgitimKayitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EgitimKayitID"));

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MezuniyetYili")
                        .HasColumnType("integer");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("Seviye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EgitimKayitID");

                    b.HasIndex("PersonelID");

                    b.ToTable("EgitimBilgileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IletisimBilgileri", b =>
                {
                    b.Property<int>("IletisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IletisimID"));

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IletisimTipiID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.HasKey("IletisimID");

                    b.HasIndex("IletisimTipiID");

                    b.HasIndex("PersonelID");

                    b.ToTable("IletisimBilgileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_BelgeKategorileri", b =>
                {
                    b.Property<int>("BelgeKategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BelgeKategoriID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BelgeKategoriID");

                    b.ToTable("Lookup_BelgeKategorileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_CalismaTipi", b =>
                {
                    b.Property<int>("CalismaTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalismaTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CalismaTipiID");

                    b.ToTable("Lookup_CalismaTipi");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_IletisimTipleri", b =>
                {
                    b.Property<int>("IletisimTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IletisimTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IletisimTipiID");

                    b.ToTable("Lookup_IletisimTipleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_MeslekKodlari", b =>
                {
                    b.Property<int>("MeslekKoduID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeslekKoduID"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeslekKoduID");

                    b.ToTable("Lookup_MeslekKodlari");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_MuhasebeHareketTipi", b =>
                {
                    b.Property<int>("HareketTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HareketTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HareketTipiID");

                    b.ToTable("Lookup_MuhasebeHareketTipi");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.MuhasebeHareketleri", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HareketID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HareketTipiID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HareketID");

                    b.HasIndex("HareketTipiID");

                    b.HasIndex("PersonelID");

                    b.ToTable("MuhasebeHareketleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonelID");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaasTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TemelMaas")
                        .HasColumnType("numeric");

                    b.HasKey("PersonelID");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.ToTable("Personel_Detay_Muhasebe");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("CalismaTipiID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IsyeriSicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SGKMeslekKoduID")
                        .HasColumnType("integer");

                    b.HasKey("PersonelID");

                    b.ToTable("Personel_Detay_SGK");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Zimmet", b =>
                {
                    b.Property<int>("ZimmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZimmetID"));

                    b.Property<string>("DemirbasAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MarkaModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ZimmetID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("SeriNo")
                        .IsUnique();

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Belgeler", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_BelgeKategorileri", "BelgeKategori")
                        .WithMany()
                        .HasForeignKey("BelgeKategoriID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("Belgeler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BelgeKategori");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.EgitimBilgileri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("EgitimBilgileri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IletisimBilgileri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_IletisimTipleri", "IletisimTipi")
                        .WithMany()
                        .HasForeignKey("IletisimTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IletisimTipi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.MuhasebeHareketleri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_MuhasebeHareketTipi", "HareketTipi")
                        .WithMany()
                        .HasForeignKey("HareketTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("MuhasebeHareketleri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HareketTipi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_Muhasebe")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_SGK")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_SGK", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Zimmet", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("Zimmetler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Navigation("Belgeler");

                    b.Navigation("EgitimBilgileri");

                    b.Navigation("IletisimBilgileri");

                    b.Navigation("MuhasebeHareketleri");

                    b.Navigation("Personel_Detay_Muhasebe");

                    b.Navigation("Personel_Detay_SGK");

                    b.Navigation("Zimmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
