// <auto-generated />
using System;
using LoyalKullaniciTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoyalKullaniciTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106062621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonelID");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaasTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TemelMaas")
                        .HasColumnType("numeric");

                    b.HasKey("PersonelID");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.ToTable("Personel_Detay_Muhasebe");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("CalismaTipiID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IsyeriSicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SGKMeslekKoduID")
                        .HasColumnType("integer");

                    b.HasKey("PersonelID");

                    b.ToTable("Personel_Detay_SGK");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_Muhasebe")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_SGK")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_SGK", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Navigation("Personel_Detay_Muhasebe");

                    b.Navigation("Personel_Detay_SGK");
                });
#pragma warning restore 612, 618
        }
    }
}
