// <auto-generated />
using System;
using LoyalKullaniciTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoyalKullaniciTakip.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107062240_AddDevamsizPuantajDurumu")]
    partial class AddDevamsizPuantajDurumu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Belgeler", b =>
                {
                    b.Property<int>("BelgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BelgeID"));

                    b.Property<string>("BelgeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BelgeKategoriID")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BelgeID");

                    b.HasIndex("BelgeKategoriID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Belgeler");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.BordroHakedisKaydi", b =>
                {
                    b.Property<int>("KayitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KayitID"));

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<decimal>("BrutMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FazlaMesaiUcreti")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("HesaplananTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("KesintiTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetHakedis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("KayitID");

                    b.HasIndex("PersonelID", "Yil", "Ay")
                        .IsUnique();

                    b.ToTable("BordroHakedisKayitlari");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.EgitimBilgileri", b =>
                {
                    b.Property<int>("EgitimKayitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EgitimKayitID"));

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MezuniyetYili")
                        .HasColumnType("integer");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("Seviye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EgitimKayitID");

                    b.HasIndex("PersonelID");

                    b.ToTable("EgitimBilgileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IletisimBilgileri", b =>
                {
                    b.Property<int>("IletisimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IletisimID"));

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IletisimTipiID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.HasKey("IletisimID");

                    b.HasIndex("IletisimTipiID");

                    b.HasIndex("PersonelID");

                    b.ToTable("IletisimBilgileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IzinTalepleri", b =>
                {
                    b.Property<int>("TalepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TalepID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IzinTipiID")
                        .HasColumnType("integer");

                    b.Property<int>("OnayDurumu")
                        .HasColumnType("integer");

                    b.Property<int?>("OnaylayanPersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TalepID");

                    b.HasIndex("IzinTipiID");

                    b.HasIndex("OnaylayanPersonelID");

                    b.HasIndex("PersonelID");

                    b.ToTable("IzinTalepleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_BelgeKategorileri", b =>
                {
                    b.Property<int>("BelgeKategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BelgeKategoriID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BelgeKategoriID");

                    b.ToTable("Lookup_BelgeKategorileri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_CalismaTipi", b =>
                {
                    b.Property<int>("CalismaTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalismaTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CalismaTipiID");

                    b.ToTable("Lookup_CalismaTipi");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_Departmanlar", b =>
                {
                    b.Property<int>("DepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmanID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmanID");

                    b.ToTable("Lookup_Departmanlar");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_GenelAyarlar", b =>
                {
                    b.Property<string>("AyarKey")
                        .HasColumnType("text");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("AyarValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AyarKey");

                    b.ToTable("Lookup_GenelAyarlar");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_IletisimTipleri", b =>
                {
                    b.Property<int>("IletisimTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IletisimTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IletisimTipiID");

                    b.ToTable("Lookup_IletisimTipleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_IzinTipleri", b =>
                {
                    b.Property<int>("IzinTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IzinTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YillikIzindenDuserMi")
                        .HasColumnType("boolean");

                    b.HasKey("IzinTipiID");

                    b.ToTable("Lookup_IzinTipleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_KidemIzinHakedis", b =>
                {
                    b.Property<int>("KidemIzinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KidemIzinID"));

                    b.Property<int>("HakedilenGunSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("MaxKidemYili")
                        .HasColumnType("integer");

                    b.Property<int>("MinKidemYili")
                        .HasColumnType("integer");

                    b.HasKey("KidemIzinID");

                    b.ToTable("Lookup_KidemIzinHakedis");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_MeslekKodlari", b =>
                {
                    b.Property<int>("MeslekKoduID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeslekKoduID"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeslekKoduID");

                    b.ToTable("Lookup_MeslekKodlari");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_Meslekler", b =>
                {
                    b.Property<int>("MeslekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeslekID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeslekID");

                    b.ToTable("Lookup_Meslekler");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_MuhasebeHareketTipi", b =>
                {
                    b.Property<int>("HareketTipiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HareketTipiID"));

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HareketTipiID");

                    b.ToTable("Lookup_MuhasebeHareketTipi");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Lookups.Lookup_PuantajDurumlari", b =>
                {
                    b.Property<int>("PuantajDurumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuantajDurumID"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PuantajDurumID");

                    b.ToTable("Lookup_PuantajDurumlari");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.MuhasebeHareketleri", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HareketID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HareketTipiID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HareketID");

                    b.HasIndex("HareketTipiID");

                    b.HasIndex("PersonelID");

                    b.ToTable("MuhasebeHareketleri");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartmanID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotografDosyaYolu")
                        .HasColumnType("text");

                    b.Property<int?>("MeslekID")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonelID");

                    b.HasIndex("DepartmanID");

                    b.HasIndex("MeslekID");

                    b.HasIndex("TCKimlikNo")
                        .IsUnique();

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaasTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TemelMaas")
                        .HasColumnType("numeric");

                    b.HasKey("PersonelID");

                    b.HasIndex("IBAN")
                        .IsUnique();

                    b.ToTable("Personel_Detay_Muhasebe");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("CalismaTipiID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IsyeriSicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SGKMeslekKoduID")
                        .HasColumnType("integer");

                    b.HasKey("PersonelID");

                    b.ToTable("Personel_Detay_SGK");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.PuantajGunluk", b =>
                {
                    b.Property<int>("PuantajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PuantajID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MesaiSaati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<int>("PuantajDurumID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PuantajID");

                    b.HasIndex("PuantajDurumID");

                    b.HasIndex("PersonelID", "Tarih")
                        .IsUnique();

                    b.ToTable("PuantajGunluk");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Zimmet", b =>
                {
                    b.Property<int>("ZimmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZimmetID"));

                    b.Property<string>("DemirbasAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MarkaModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ZimmetID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("SeriNo")
                        .IsUnique();

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Belgeler", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_BelgeKategorileri", "BelgeKategori")
                        .WithMany()
                        .HasForeignKey("BelgeKategoriID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("Belgeler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BelgeKategori");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.BordroHakedisKaydi", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.EgitimBilgileri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("EgitimBilgileri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IletisimBilgileri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_IletisimTipleri", "IletisimTipi")
                        .WithMany()
                        .HasForeignKey("IletisimTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IletisimTipi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.IzinTalepleri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_IzinTipleri", "IzinTipi")
                        .WithMany()
                        .HasForeignKey("IzinTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "OnaylayanPersonel")
                        .WithMany()
                        .HasForeignKey("OnaylayanPersonelID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("IzinTalepleri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IzinTipi");

                    b.Navigation("OnaylayanPersonel");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.MuhasebeHareketleri", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_MuhasebeHareketTipi", "HareketTipi")
                        .WithMany()
                        .HasForeignKey("HareketTipiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("MuhasebeHareketleri")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HareketTipi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_Departmanlar", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_Meslekler", "Meslek")
                        .WithMany()
                        .HasForeignKey("MeslekID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departman");

                    b.Navigation("Meslek");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_Muhasebe")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_Muhasebe", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel_Detay_SGK", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithOne("Personel_Detay_SGK")
                        .HasForeignKey("LoyalKullaniciTakip.Data.Personel_Detay_SGK", "PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.PuantajGunluk", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("PuantajGunlukKayitlari")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoyalKullaniciTakip.Data.Lookups.Lookup_PuantajDurumlari", "PuantajDurum")
                        .WithMany()
                        .HasForeignKey("PuantajDurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("PuantajDurum");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Zimmet", b =>
                {
                    b.HasOne("LoyalKullaniciTakip.Data.Personel", "Personel")
                        .WithMany("Zimmetler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("LoyalKullaniciTakip.Data.Personel", b =>
                {
                    b.Navigation("Belgeler");

                    b.Navigation("EgitimBilgileri");

                    b.Navigation("IletisimBilgileri");

                    b.Navigation("IzinTalepleri");

                    b.Navigation("MuhasebeHareketleri");

                    b.Navigation("Personel_Detay_Muhasebe");

                    b.Navigation("Personel_Detay_SGK");

                    b.Navigation("PuantajGunlukKayitlari");

                    b.Navigation("Zimmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
